### ISSUE TITLE
调整内容结构

### ISSUE THREAD

**Issue by 46135621** [camera-2018/hdu-cs-wiki#10]
推荐把 4.6.5.2经典网络上调，而不是放在cv子模块中

**Comment by 46135621** [comment]
思考了一下，感觉经典网络和数据预处理部分改名较好，而不是上调，因为讲述的内容很多关于cv，应当补充nlp方面的网络，如XLNet，RNN，BERT，seq2seq

**Comment by 46135621** [comment]
数据预处理部分应当放在网络之前

**Comment by camera-2018** [comment]
chored it by #11
