### ISSUE TITLE
链接定向出错

### ISSUE THREAD

**Issue by 46135621** [camera-2018/hdu-cs-wiki#16]
![image](https://user-images.githubusercontent.com/87229030/233338217-9704467b-fc36-4810-b576-d9fffa9210b3.png)
![image](https://user-images.githubusercontent.com/87229030/233338250-1c7f0fe1-c941-4707-a832-f8a912499935.png)
回飞书了

**Comment by camera-2018** [comment]
正常的 没改 你可以改成直接相对于md的链接

**Comment by camera-2018** [comment]
0fa327d37db7295a26d4435830b1db564ff8fcf0
修了所有的🤧
