### ISSUE TITLE
2.1.1 ‘现状’部分文本来源于上海交通大学学生生存手册， 但并没有标明为引用内容

### ISSUE THREAD

**Issue by LiAuTraver** [camera-2018/hdu-cs-wiki#177]
卿引文出自上海交通大学学生生存手册之“悲壮的学习方式”部，但未标明引用，仅删去助词，不知编者有意为之否，若遭他人揭露，或视为抄袭，则本校名誉及地位恐难保矣。

**Comment by camera-2018** [comment]
昔日笔下流转，非出自己独创，源于上海交通大者之智，非有抄袭之意，今已悉数标明，愿海涵天宽，再获宽恕。

fix: 314a4ec9afc14fa893caad6213f33b92eb3d9486

**Comment by LiAuTraver** [comment]
蒙先生即时回函，谨表谢意。昔者所陈之言，实出于对于文献引用之略见疑虑，非敢妄揣先生剽窃抄袭之心。今悉闻先生解释，并已添加标注，实为为学之态度，予甚为欣慰。

谨此回函，表明并非怀疑先生抄袭之意。先生以经验之泉源，滋润后学若川流。吾等后生蒙君深厚之恩典，心怀感激之念。
