### ISSUE TITLE
4.6.6.2.2 基于数据看推荐系统内容待补充

### ISSUE THREAD

**Issue by buwyi** [camera-2018/hdu-cs-wiki#28]
4.6.6.2.2 基于数据看推荐系统内容待补充

**Comment by camera-2018** [comment]
> 4.6.6.2.2 基于数据看推荐系统内容待补充

没懂 这部分缺东西吗

**Comment by camera-2018** [comment]
4.6.6.2.2.3 修了 在 17d425a114001885f7bd8cd6a36ad8907a4415f2

**Comment by buwyi** [comment]
> 

因为还在写还没更新呢qwq2.6.6.2.2后面还有五六个文档大概

**Comment by camera-2018** [comment]
🤔写哪儿了

**Comment by buwyi** [comment]
> 🤔写哪儿了

新建文件夹，qwq

**Comment by camera-2018** [comment]
那给你打标签了
![image](https://user-images.githubusercontent.com/40380042/233766056-23b9ece4-0edc-48be-b5dc-72b090339a23.png)
