### ISSUE TITLE
建议增加类似导读模块，因为讲义不是从前到后贯穿连续的，新生拿到这玩意会不知道从何看起

### ISSUE THREAD

**Issue by creamm-kk** [camera-2018/hdu-cs-wiki#31]
比如先看电专生存指南，高效学习，然后可以看看第三章并且找找自己喜欢的方向，去看对应的章节之类的，然后人工智能模块过于庞大，也建议加入导读

**Comment by creammmmmmmmmmmmmmmm** [comment]
ai的导读我会尝试做一下，但是我不会编辑md文件，我先去原来那个飞书里面写写🤔

**Comment by creammmmmmmmmmmmmmmm** [comment]
> ai的导读我会尝试做一下，但是我不会编辑md文件，我先去原来那个飞书里面写写🤔

我在飞书里面4.人工智能 的   前言部分的末尾加入了一个粗略的导读，其中最后一部分等待ZZM完善 @HanWu311 ，加进来的时候记得添加链接
