### ISSUE TITLE
可以添加下让虚拟机也可以上谷歌的方法

### ISSUE THREAD

**Issue by S1-19027** [camera-2018/hdu-cs-wiki#331]
参考：https://skfwe.cn/p/clash%E8%AE%A9%E8%99%9A%E6%8B%9F%E6%9C%BA%E7%B3%BB%E7%BB%9Flinux-%E5%85%B1%E4%BA%AB%E4%B8%BB%E6%9C%BA%E7%9A%84%E4%BB%A3%E7%90%86/

**Comment by camera-2018** [comment]
原则上不教学代理软件的使用方法🤕
