### ISSUE TITLE
友链申请：西邮Wiki

### ISSUE THREAD

**Issue by L33Z22L11** [camera-2018/hdu-cs-wiki#350]
我是[西邮Wiki](https://github.com/xupt-wiki/xupt-wiki)仓库的维护者纸鹿，很高兴能看到hdu-cs-wiki这样内容丰富的Wiki。西邮Wiki希望与hdu-cs-wiki互加友链，共同促进校园Wiki生态发展。

**Comment by camera-2018** [comment]
🤓👍 已加友情链接 via 972d454fb1e23c702d8fabea37689f749fa0aeb6

我很早 star 了西邮 wiki，觉得 h1h2 标题那个 icon 背景虚化既简洁又美观 还有大佬的博客设计也很帅😽
