### ISSUE TITLE
修一下404链接~

### ISSUE THREAD

**Issue by aFlyBird0** [camera-2018/hdu-cs-wiki#68]
broken links 都在这里了：https://github.com/aFlyBird0/hdu-cs-wiki/actions/runs/5606434495

如果有些链接想屏蔽掉，不加入检查列表，可以在根目录的 `.lycheeignore` 中加几行规则，正则语法。

直接commit了然后提pr，每次commit都会自动检查的

**Comment by camera-2018** [comment]
🥳

**Comment by camera-2018** [comment]
Fixed via #70
