### ISSUE TITLE
右侧目录显示错误

### ISSUE THREAD

**Issue by 4nsw3r123** [camera-2018/hdu-cs-wiki#69]
https://hdu-cs.wiki/6.%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%AE%89%E5%85%A8/6.2.3%E6%BC%8F%E6%B4%9E%E6%8C%96%E6%8E%98%E3%80%81%E6%BC%8F%E6%B4%9E%E5%88%A9%E7%94%A8.html
页面内只有一级标题可以在右侧显示
![image](https://github.com/camera-2018/hdu-cs-wiki/assets/72328038/d705bd51-8091-4c6a-b035-465e42e5ee47)

**Comment by camera-2018** [comment]
![image](https://github.com/camera-2018/hdu-cs-wiki/assets/40380042/622c68ef-0c56-4f2c-8388-5a36eb34d014)
修了  via 62aa22fd43fce237220abe005809617cce44da14

**Comment by 4nsw3r123** [comment]
怎么只修了这一个，剩下的所有页面都有这个问题
