### ISSUE TITLE
多人博客

### ISSUE THREAD

**Issue by MarleneJiang** [camera-2018/hdu-cs-wiki#73]
建立一个新栏目，主要内容是多人博客的聚合，主要提供一些技术更为深层，更前沿，还未自成体系的一些内容。
聚合采用RSS，页面主要基于vitepress风格ui

**Comment by MarleneJiang** [comment]
[Commit](https://github.com/camera-2018/hdu-cs-wiki/commit/280929213fd62348b0aaecf0bac56ef88d313a4f)

请原谅我速成博客而写的一坨屎，麻烦ts喵大人帮我完善字体颜色，以及我明明设置了`aside: false`却没起效果的问题~
```md
---
title: Blogs
editLink: false
aside: false
---
```

**Comment by MarleneJiang** [comment]
# 目前具有的功能

- 博客人员名单
- 博客文章列表
- 分页以及换页及自适应
- 暗黑模式适应

<img width="1171" alt="25f995c7f5ca487f69e1f809ee09844c" src="https://github.com/camera-2018/hdu-cs-wiki/assets/49270362/1f6528cf-d7e7-4067-84b1-dba2911a5d7b">
![image](https://github.com/camera-2018/hdu-cs-wiki/assets/49270362/ec350abc-f858-45b2-a5c8-d87964e7b9f1)

**Comment by camera-2018** [comment]
> [Commit](https://github.com/camera-2018/hdu-cs-wiki/commit/280929213fd62348b0aaecf0bac56ef88d313a4f)
> 
> 请原谅我速成博客而写的一坨屎，麻烦ts喵大人帮我完善字体颜色，以及我明明设置了`aside: false`却没起效果的问题~
> 
> ```
> ---
> title: Blogs
> editLink: false
> aside: false
> ---
> ```
> 
> @camera-2018

aside是右侧导航某文章的head导航目录喵

**Comment by MarleneJiang** [comment]
> > [Commit](https://github.com/camera-2018/hdu-cs-wiki/commit/280929213fd62348b0aaecf0bac56ef88d313a4f)
> > 请原谅我速成博客而写的一坨屎，麻烦ts喵大人帮我完善字体颜色，以及我明明设置了`aside: false`却没起效果的问题~
> > ```
> > ---
> > title: Blogs
> > editLink: false
> > aside: false
> > ---
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @camera-2018
> 
> aside是右侧导航某文章的head导航目录喵

抱歉喵
